### ISSUE TITLE
Option for backing up without listing packages

### ISSUE THREAD

**Issue by ghost** [MrAlpha786/termux-backup-restore#11]
I like my backups clean, so I want this feature to exist (Or remove the functionality of listing packages when backing up).
Or maybe there was a bug? I still have not read the changes made to the program so I still not know.
Nevertheless I want the feature to provide an option to not list packages.

**Comment by MrAlpha786** [comment]
Hey,

I know there is a lot to improve. But this is your personal preference to not have a list of your previously installed packages. 
In my opinion, a single file in home directory will have no significant effect on backup. And because the script cannot restore PREFIX safely in some cases. And there is no option to do this now, it is safe to have that list.

Honestly, I am not being rude but there was no need to open such an issue. Because that's not a bug, just a failsafe. And If you still don't want that list, just remove that single line. It's in the backup function.

You are welcome if you find any bug or have some ideas to improve the script. And remember what I said previously the idea is one simple script. What this script do can be done in a single command. Complicating it, is unnecessary.
